### ISSUE TITLE
Error while updating property 'height' in shadow node of type: VRTVideoSurface

### ISSUE THREAD

**Issue by LimitedDani** [ReactVision/viro#302]
## Description
When setting height, width on VRVideo or any other component on android I get this error:
`FATAL EXCEPTION: mqt_native_modules
                                                                                com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'height' in shadow node of type: VRTVideoSurface
                                                                                	at com.facebook.react.uimanager.e2$m.d(SourceFile:117)
                                                                                	at com.facebook.react.uimanager.y1$a.c(SourceFile:11)
                                                                                	at com.facebook.react.uimanager.y1.f(SourceFile:37)
                                                                                	at com.facebook.react.uimanager.n0.s0(SourceFile:1)
                                                                                	at com.facebook.react.uimanager.d1.j(SourceFile:76)
                                                                                	at com.facebook.react.uimanager.UIManagerModule.createView(SourceFile:54)
                                                                                	at com.facebook.react.uimanager.ReanimatedUIManager.createView(SourceFile:1)
                                                                                	at java.lang.reflect.Method.invoke(Native Method)
                                                                                	at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:151)
                                                                                	at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:20)
                                                                                	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:1)
                                                                                	at android.os.Looper.loop(Looper.java:214)
                                                                                	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:38)
                                                                                	at java.lang.Thread.run(Thread.java:919)
                                                                                Caused by: java.lang.reflect.InvocationTargetException
                                                                                	at java.lang.reflect.Method.invoke(Native Method)
                                                                                	at com.facebook.react.uimanager.e2$m.d(SourceFile:52)
                                                                                	at com.facebook.react.uimanager.y1$a.c(SourceFile:11) 
                                                                                	at com.facebook.react.uimanager.y1.f(SourceFile:37) 
                                                                                	at com.facebook.react.uimanager.n0.s0(SourceFile:1) 
                                                                                	at com.facebook.react.uimanager.d1.j(SourceFile:76) 
                                                                                	at com.facebook.react.uimanager.UIManagerModule.createView(SourceFile:54) 
                                                                                	at com.facebook.react.uimanager.ReanimatedUIManager.createView(SourceFile:1) 
                                                                                	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                	at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:151) 
                                                                                	at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:20) 
                                                                                	at com.facebook.jni.NativeRunnable.run(Native Method) 
                                                                                	at android.os.Handler.handleCallback(Handler.java:883) 
                                                                                	at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:1) 
                                                                                	at android.os.Looper.loop(Looper.java:214) 
                                                                                	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:38) 
                                                                                	at java.lang.Thread.run(Thread.java:919) 
                                                                                Caused by: java.lang.IllegalAccessError: Illegal class access ('com.viromedia.bridge.component.node.VRTNodeManager$a' attempting to access 'com.facebook.react.bridge.DynamicFromMap') in attempt to invoke static method com.facebook.react.bridge.DynamicFromMap com.facebook.react.bridge.DynamicFromMap.create(com.facebook.react.bridge.ReadableMap, java.lang.String) (declaration of 'com.viromedia.bridge.component.node.VRTNodeManager$a' appears in base.apk!classes2.dex)
                                                                                	at com.viromedia.bridge.component.node.VRTNodeManager$a.setHeight(SourceFile:45)
                                                                                	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                	at com.facebook.react.uimanager.e2$m.d(SourceFile:52) 
                                                                                	at com.facebook.react.uimanager.y1$a.c(SourceFile:11) 
                                                                                	at com.facebook.react.uimanager.y1.f(SourceFile:37) 
                                                                                	at com.facebook.react.uimanager.n0.s0(SourceFile:1) 
                                                                                	at com.facebook.react.uimanager.d1.j(SourceFile:76) 
                                                                                	at com.facebook.react.uimanager.UIManagerModule.createView(SourceFile:54) 
                                                                                	at com.facebook.react.uimanager.ReanimatedUIManager.createView(SourceFile:1) 
                                                                                	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                	at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:151) 
                                                                                	at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:20) 
                                                                                	at com.facebook.jni.NativeRunnable.run(Native Method) 
                                                                                	at android.os.Handler.handleCallback(Handler.java:883) 
                                                                                	at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:1) 
                                                                                	at android.os.Looper.loop(Looper.java:214) 
                                                                                	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:38) 
                                                                                	at java.lang.Thread.run(Thread.java:919) 
`

`            <ViroVideo
              source={{
                uri: videoUri,
              }}
              width={0.14}
              height={(0.14 / 16) * 9}
              paused={!isPlaying}
              onPinch={(pinchState, scaleFactor) => {
                setScale(() => [scaleFactor, scaleFactor, scaleFactor]);
              }}
            />`

Using:
"@reactvision/react-viro": "^2.41.6",

**Comment by jirka-oone** [comment]
this works https://github.com/ReactVision/viro/pull/318/files for us, react-native 76.5 in old architecture
